### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by ramondunker** [joogps/My-Processing-Sketches#1]
Hey,

I don't think I can send you a private message on GitHub, so I'm using one of your repo's :P.
I thought maybe it's a good idea to create a Trello board to keep up with all the updates regarding the panasonic_viera integration. I'd like to help you but I don't know what has to be done. If you want to join the board you can click on the following link:

https://trello.com/invite/b/wI9ZGD8T/2493c2aa762abe9b6e271055b5c6bad4/panasonicviera

If you want to contact me you can send me an email at info@ramondunker.nl

Best regards,

Ramon

**Comment by joogps** [comment]
@ramondunker Oh my god, I'm so sorry I didn't see this (GitHub wasn't notifying me for some reason)

Do you still think the Trello board would be useful now that the pull request was accepted? I mean, there's still work to do anyways... Never mind, I’ll use it!

(I completely agree with you, GitHub should have a direct message platform)

**Comment by ramondunker** [comment]
Hey @joogps, no problem man.

If I can be of any help to you please let me know by sending me an email :)
